# Recreate the package's synthetic example dataset.
# Run from the package root after loading the development package.

transientExample <- simulateTransientDTU(
    n_genes = 12,
    n_stages = 8,
    n_replicates = 2,
    signal = 0.35,
    noise_sd = 0.01,
    seed = 20260823
)

feature_ids <- rownames(transientExample$usage)
gene_ids <- sub("_tx[12]$", "", feature_ids)

transientExampleSE <- SummarizedExperiment::SummarizedExperiment(
    assays = list(usage = transientExample$usage),
    rowData = S4Vectors::DataFrame(
        feature_id = feature_ids,
        gene_id = gene_ids,
        gene_name = gene_ids,
        row.names = feature_ids
    ),
    colData = S4Vectors::DataFrame(transientExample$col_data),
    metadata = list(
        stage_order = transientExample$stage_order,
        groups = transientExample$groups,
        truth = S4Vectors::DataFrame(transientExample$truth),
        gene_truth = S4Vectors::DataFrame(transientExample$gene_truth),
        simulation_parameters = transientExample$simulation_parameters,
        provenance = paste(
            "Synthetic known-truth data generated by simulateTransientDTU();",
            "seed 20260823; no study participants or biological measurements."
        )
    )
)

transientExamplePairwise <- S4Vectors::DataFrame(transientExample$pairwise)

save(
    transientExample,
    file = file.path("data", "transientExample.rda"),
    compress = "xz",
    version = 3
)

save(
    transientExampleSE,
    file = file.path("data", "transientExampleSE.rda"),
    compress = "xz",
    version = 3
)

save(
    transientExamplePairwise,
    file = file.path("data", "transientExamplePairwise.rda"),
    compress = "xz",
    version = 3
)
